Estilos home
FrancoGL/ISPC-Mobile pull request #150
Opened 2023-10-21 20:46 UTC by Sole1988

2023-10-21 21:23 UTC, FrancoGL approved these changes

2023-10-23 14:22 UTC, FrancoGL requested changes
@Sole1988 falta actualizar con develop

2023-10-25 21:22 UTC, Sole1988 commented
Dale, ahora lo veo Graciassss

2023-10-25 21:28 UTC, FrancoGL approved these changes

2023-10-25 22:50 UTC, merged